name: Pyinstaller build 

on: [workflow_dispatch]

jobs:
  pyinstaller-build:
    strategy:
        fail-fast: false
        matrix:
          build: [
            {os: macos-latest, name: 'whisper-server-macos-arm'},
            {os: macos-13, name: 'whisper-server-macos-x64'},
            {os: windows-latest, name: 'whisper-server-win'}
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: ${{ matrix.build.name }}
          options: --onefile, --name "Whisper Server", 